romgrk/barbar.nvim

- README.md
- doc/barbar.txt
- plugin/bufferline.vim
Hi,
I'm working with fairly narrow terminals at the minute - I love the bar, but I don't really want four spaces either side of the tab name.
This PR is just to make that value configurable (in the `g:bufferline` object).
If you don't want folks messing around with your configuration object, feel free to reject this.
Also, in the same way that you're using `extend()` to make the `bufferline` object configurable [here](https://github.com/romgrk/barbar.nvim/blob/master/plugin/bufferline.vim#L50). I thought it would be nice to make to the `g:icons` object configurable in the same way [here](https://github.com/BodneyC/barbar.nvim/blob/master/plugin/bufferline.vim#L102); at the minute, `g:icons` is just overridden.
> feat(padding): Set configurable padding (and separators)

- autoload/bufferline/tabpages.vim
- lua/bufferline/layout.lua
- lua/bufferline/render.lua
The `nvim_get_current_tabpage` function reports incorrect counts tab pages. Using `tabpagenr()` reports correctly as discovered by @Melkster [here](https://github.com/romgrk/barbar.nvim/issues/22#issuecomment-727072619), so I adjusted the usages.
Tested on my machine to validate.
> Use tabpagenr instead of nvim api func

- README.md
- autoload/bufferline/highlight.vim
- doc/barbar.txt
- lua/bufferline/get-icon.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- plugin/bufferline.vim
I added the highlight group `BufferTabpageFill` to define the space between buffers and the tabpage count.
Here's a screenshot:
Closes #57.
___
Edit: Since the scope of the PR has increased, here is a list of things that have been adjusted:
* Match background of `DevIcon*` highlight groups to `Buffer<status>` groups.
* Add `BufferTabpageFill` for customization of the space between `BufferTabpages` and `Buffer<status>`
* `autocmd BufNewFile` to update names of buffers.
* `printf()` command fix for transforming RGB→Hex color codes using `nvim_get_hl_by_name()`.
* Document changes.
I think that's everything but if I missed something let me know.
> Add separate highlight group for tabpage spacer

- lua/bufferline/state.lua
Currently when for instance doing `:BufferGoto 5` with only four buffers Vim throws an error. Now Vim will be silent instead.
> fix: BufferGoto throws error

- lua/bufferline/state.lua
- plugin/bufferline.vim
Modify `:BufferNext`/`:BufferPrevious` to use a count to determine the number of steps to jump to get to the next/previous buffer. Defaults to 1/-1.
For instance with the recommended mappings `<A-.>` and `<A-,>` for `:BufferNext`/`:BufferPrevious` one could for example do `3<A-.>` to jump to the third next buffer. If the count to `BufferNext` exceeds the total number of buffers it wraps around and keeps counting from the first buffer as one would expect, and vice versa for `BufferPrevious`.
> Allow BufferNext/BufferPrevious to use count

- README.md
The following is correct?
`buffline` -> `bufferline `
> Fix typo errors

- README.md
- autoload/bufferline/highlight.vim
- doc/barbar.txt
- lua/bufferline/render.lua
- plugin/bufferline.vim
This PR adds the ability to set icon highlight groups. The main purpose is to allow consistent colors across icons. Since this was previously mentioned in #92, I figured others would also be interested in having this as a built-in option.
To enable the icon highlight groups, `icon_custom_colors` has to be set. Since the majority probably want the default web-devicons colors, this option is `false` by default. This should also avoid messing with existing configurations.
I also added the `Index` highlight groups to the README since they appeared to be missing.
> Add icon highlight groups

- autoload/bufferline/highlight.vim
The default bg color is `#000000`, this can look weird, when the background color is set to `NONE` ie. the background is transparent.
This PR changes it to `NONE`. This shouldn't change the current behavior, if a colorscheme sets it to a different value.
See here:
> feat: change default background color to `none` instead of `#000000`

- doc/barbar.txt
Latest commit removes the duplicate but now the tag is non-existant.
This PR adds the now missing helper tag to the table of contents.
Also standardizes the heading spacing
> Add missing helper-tag, standardize heading spacing

- lua/bufferline/state.lua
- plugin/bufferline.vim
Now it matches the behavior of BufferNext and BufferPrev, except it will clamp the position to the start/end instead of wrapping.
The table insert/remove will be slightly less efficient than the element swap, but it shouldn't matter for most cases (<100 buffers open). If performance is a concern I can add a special case to do the element swap if we're only moving it by 1 slot.
> Allow BufferMoveNext/Prev to specify a count

- lua/bufferline/state.lua
- plugin/bufferline.vim
Functions similarly to BufferGoto, but moves the current buffer to the desired destination. I used to often use `:tabm` to move my tabs around, and wanted some analog in barbar.
> Add a BufferMove command to position a buffer absolutely

- lua/bufferline/state.lua
- plugin/bufferline.vim
I noticed that when I save and load sessions the buffers come back in a somewhat arbitrary order. Right now this is just restoring `m.buffers`, and from my tests that seems to work fine. Is there anything else that you think I would need to save/restore from the state while I'm at it, like `buffers_by_id` or possibly `scroll`?
> Integrate with vim-session to save buffer order

- README.md
- doc/barbar.txt
- lua/bufferline/layout.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- plugin/bufferline.vim
Addresses #84
The mental model is pretty simple:
* Users can "pin" a buffer.
* "pinned" buffers always appear to the left of unpinned buffers
I updated the UI to show the pin status with an icon
Or without, if the user doesn't have nerd fonts
Does this seem like a feature that you would want to add to barbar? Does it make sense as is or would you prefer to tweak how it works?
Also there's a small merge conflict with my other PR, so if you like both of them merge the other one first and I'll resolve it here.
> Feature: 'pinned' buffers similar to chrome tabs

- lua/bufferline/state.lua
- plugin/bufferline.vim
This is useful when the layout changes such that the tabline order no longer matches the window number order (e.g., swapping windows `<c-w><c-r>`).
This covers part of what I mentioned in https://github.com/romgrk/barbar.nvim/issues/155.
> Add ordering by window number

- README.md
- doc/barbar.txt
- lua/bufferline/state.lua
- plugin/bufferline.vim
As [suggested](https://github.com/romgrk/barbar.nvim/pull/145#issuecomment-891620255) this is the MR to add the ":BufferCloseAllButPinned" functionality.
This command makes use of the new "pin" functionality.
It will close all open buffers but the pinned ones.
> Add BufferCloseAllButPinned command

- autoload/bufferline/bbye.vim
- plugin/bufferline.vim
To get Vim to ask you if you want to close a modified buffer, you have to add `set confirm` in your config file.
This allows using `:confirm BufferClose` instead, which is in line with the builtin `:confirm bdelete` method.
> Support ":confirm BufferClose"

- lua/bufferline/buffer.lua
This fixes a bug introduced by #181 which causes an infinite recursion and a crash when a buffer name exceeds the maximum length.
This was detailed in LunarVIM: https://github.com/LunarVim/LunarVim/issues/1636
The error:
---
A simplified reproduction using the new (fixed) and old (broken) trimmed name code has these results:
``` markdown
ext_index: 83
max_len - ext_index: -53
path 2, invalid extension
name len:  30
trimmed name:  main.lua \$* >> sumneko-lua…
name len:  13
trimmed name:  highlight.vim
ext_index: 4
max_len - ext_index: 26
valid extension
name len:  30
trimmed name:  super-really-very-long-….vim
name len:  121
trimmed name:  main.lua \$* >> sumneko-lua-languag….lua \$* >> sumneko-lua-language-server^@^@  chmod +x sumneko-lua-language-server^@
name len:  13
trimmed name: …
```
> Fix trimmed name recursion due to exceeding length

- README.md
Replace square brackets `[]` with `{}` curly for lists.
> docs: update README.md, Lua sample config

- lua/bufferline/jump_mode.lua
After activating `buffer pick`, if Ctrl-c is pressed the following error occurs.
```
E5108: Error executing lua Keyboard interrupt                                                                                                                                                                                                               
stack traceback:                                                                                                                                                                                                                                            
[C]: in function 'getchar' …
```
> fix: keyboard interrupt error for buffer pick

- README.md
- doc/barbar.txt
- lua/bufferline/state.lua
- plugin/bufferline.vim
Fix the function `close_buffers_right()` and make the command `:BuffCloseBuffersRight` work (mentioned in issue [#214](https://github.com/romgrk/barbar.nvim/issues/214#issue-1117525872) ).
> Fix `close_buffers_right()` and add `:BufferCloseAllButCurrentOrPinned`

- README.md
- doc/barbar.txt
- lua/bufferline/layout.lua
- lua/bufferline/render.lua
Hi all,
I didn't see a way of modifying the configuration to allow the use of both  `buffer_number` _and_ `icon` at the same time. This small pull request allows the user to do just that. Probably a small use-case, but it's one I wanted and thought others should have access to as well.
I also believe I updated the documentation in all the appropriate places, but I'm not very familiar with the docs in this projects so I may have missed some. Happy to make corrections as needed.
Cheers,
Jake
> Enable use of both buffer_number & icon simultaneously

- lua/bufferline/render.lua
I figured out a better solution after merging #236. I don't think there were any bugs with it but I might as well simplify it, since it will be impossible for the logic of the renderer to be manipulated by the width of invisible characters with this implementation
> ref(render): move santizing to `groups_to_string`

- lua/bufferline/highlight.lua
- lua/bufferline/icons.lua
- lua/bufferline/utils.lua
Sometimes barbar.nvim loads before the user's preferred `termguicolors` is set; this could especially happen if they lazy load their configuration until after barbar.nvim sets itself up with the `plugin/bufferlin.lua` file.
I was aware that this bug could occur, however I was ~~lazy~~ hoping that I could save performance by only setting highlights for the current `termguicolors`.
~~__Note:__ the diff will look better after merging #258~~
Closes #256
> fix: set highlights for both `cterm` and `gui` on startup

- lua/bufferline.lua
- lua/bufferline/jump_mode.lua
This is also a performance improvement.
Closes #266.
> fix(bufferline): `redraw`ing whole screen when only `&tabline` changed

- lua/bufferline.lua
- lua/bufferline/jump_mode.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
This PR adds scrolling the bufferline via `<COUNT>BufferScrollLeft`/`Right`.
To accomplish this, a new parameter to several functions had to be added: `refocus`. On master, barbar.nvim will default to always keeping the current buffer in view— but to scroll very far you have to be able to stop this from happening temporarily.
A side effect of this was flattening a few aliases in order to reduce the odds of any changes to `render` not having their options supported by one or two specific functions (which would be challenging to figure out if missed)
Closes #54
> feat: `BufferScrollLeft`/`Right`

- README.md
Alright, so the problem with the current solution is that `nvim_win_get_width(0)` returns the width for the *current* window. Why? Because when we open file in the tree, it focuses the editor window, which is not what we want.
Instead, according to the [readme](https://github.com/kyazdani42/nvim-tree.lua#tips--tricks) of the nvim-tree plugin, `require"nvim-tree.view".View` returns a very useful set of info, among which, its width.
Tested:
1. Opened vim with one buffer
2. Toggle the tree (resized correctly)
3. Open file from the tree
4. Open folder from the tree
> nvim-tree integration fix

- lua/bufferline/highlight.lua
- lua/bufferline/icons.lua
- lua/bufferline/utils.lua
The order in which a user configures their colorscheme, barbar, and custom `:hi` groups could cause highlighting to break in certain cases (see the issue related to this PR).
Closes #281.
> fix: config init causes improper highlighting

- lua/bufferline/render.lua
`@return` uses `<type> <name>`, whereas `@param` uses `<name> <type>`. I accidentally confused the two here.
> docs(render): minor LSP annotation fix

- lua/bufferline.lua
- lua/bufferline/api.lua
- lua/bufferline/buffer.lua
- lua/bufferline/jump_mode.lua
- lua/bufferline/layout.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
This plugin has had some pretty persistent problems with lazy loading (#293, #292, #281, #218, etc).
Most of these stem from the fact that many users opt to overwriting `vim.g.bufferline` themselves, and sometimes (due to variances in configuration) this occurs _after_ our `plugin/bufferline.lua` file has called the initial `bufferline.setup()` function. This means that we end up with a `vim.g.bufferline` which has no default values, and thus when we rightly assume that they will be present, errors start getting thrown at the user.
To solve this, I created an `options` module which resolves the correct value for each setting when it is accessed, rather than at `setup`. This _does_ incur a bit of overhead, but I think it will be worth it in the end if we can finally be rid of these issues! …
> fix: lazy loading

- lua/bufferline.lua
- lua/bufferline/icons.lua
It seems that it is possible for `nil` values to mess with some of the hard-coded `g:bufferline` accesses.
> fix: ensure `vim.g.bufferline` is always non-`nil` during init

- lua/bufferline/state.lua
In Neovim 0.8, there is a new function `vim.deprecate` which does what we are looking for. I added a gate to ensure that calling this function will not error on older versions of Neovim.
> ref(state): use `vim.deprecate` if possible

- lua/bufferline.lua
- lua/bufferline/bbye.lua
It has better performance, and also decreases the chance that we could ever mess with the VimL generation in the future.
> perf(bbye): use `vim.cmd.bdelete` on Neovim 0.8+

- lua/bufferline/api.lua
Doing `:BufferGoto -1` (or any other negative index) threw an error
> fix: incorrectly handled negative :BufferGoto index

- lua/bufferline/render.lua
Not sure if anyone is experiencing this. When `:BufferClose`, the tabline doesn't get updated, and it looks kinda funny.
not sure if there is other way to fix this.
neovim-0.9.0~ubuntu1+git202210141434-81986a734-333b5866f
```lua
local bufferline = require('bufferline')
bufferline.setup({
animation = true,
icon_custom_colors = true,
maximum_padding = 2,
})
vim.api.nvim_set_keymap('n', '<A-,>', ':BufferPrevious<CR>', {silent=true, noremap=true})
vim.api.nvim_set_keymap('n', '<A-.>', ':BufferNext<CR>', {silent=true, noremap=true})
vim.api.nvim_set_var('mapleader', ',')
-- Re-order to previous/next
vim.api.nvim_set_keymap('n', '<A-Left>', ':BufferMovePrevious<CR>', {silent=true, noremap=true})
vim.api.nvim_set_keymap('n', '<A-Right>', ':BufferMoveNext<CR>', {silent=true, noremap=true})
for i …
```
> redraw tabline when render.update

- lua/bufferline/render.lua
Closes #312
Sidenote, but I am not convinced that `xolox/vim-session` is properly integrated by the code in this `User` autocommand. I searched the repo, and apparently the _only_ references to `session_save_commands` on GitHub are from `barbar.nvim`. So where did it even come from?
We might want to look at removing it at some point.
> fix(render): nvim-session-manager incompatability

- README.md
- doc/barbar.txt
- lua/bufferline/api.lua
- lua/bufferline/buffer.lua
- lua/bufferline/layout.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
Closes #155
Example, which hides inactive buffers:
```lua
require'bufferline'.setup {
hide = {inactive = true},
}
```
> feat: hide buffers

- lua/bufferline/render.lua
Update barbar on BufEnter and BufNew.
Previously Barbar only updates on BufNew, so renamed files may not be updated on time (for example, when file is renamed by ranger).
This fixes the issue #319.
> fix(render): update barbar on BufEnter to show renamed files correctly

- lua/bufferline/state.lua
The `state.offset.text` was made non-`nil` in #297, but:
1. the docs were not updated to reflect that, and
2. the `offset` table is initialized with a `nil` text field.
That could cause a bug (that I am surprised has not happened). This fixes that.
---
Also changes the `@param foo nil|<TYPE>` style doc in `state.set_offset` to `@param foo? <TYPE>` that is seen elsewhere in the project.
> fix(state): offset text can be `nil`

- lua/bufferline/render.lua
This fixes the bug that I experienced. Since I wasn't able to reproduce the original bug (possibly because we use different session management tools), I might have to modify this to do:
```lua
create_autocmd('SessionLoadPost', {
callback = function() schedule(function() render.update(true) end) end,
group = augroup_bufferline_update,
})
```
…depending on your feedback.
Closes #322.
> fix(render): no file names after loading session

- lua/bufferline/render.lua
- lua/bufferline/state.lua
Neovim on ARM is shipped with Lua5.1 instead of LuaJIT so this patch fix this compatibility issues:
- Calling xpcall with function parameters
- _G.jit does not exist
> Compatibility issue with Lua5.1

- README.md
- doc/barbar.txt
- lua/bufferline/buffer.lua
- lua/bufferline/icons.lua
- lua/bufferline/layout.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
Hide file extensions with the following option:
```lua
require'bufferline'.setup {hide = {extensions = true}}
```
Disabled by default.
Closes #67.
> feat: option to exclude file extensions from buffer name

- lua/bufferline.lua
The `state.move_current_buffer_to` function has a bug when the current buffer is not the the tabline, instead of doing nothing because the current buffer is not in the list, it removes the first buffer from the list, pushing it back to the last position when the buffer is re-added later on.
Also, create a command BufferMoveStart that uses this function. See use case in #284 (and investigation of the above issue)
> Add BufferMoveStart command

- README.md
- doc/barbar.txt
- lua/bufferline/api.lua
- lua/bufferline/buffer.lua
- lua/bufferline/highlight.lua
- lua/bufferline/jump_mode.lua
- lua/bufferline/layout.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
This feature is opt-_in_ right now, but I'm open to making it opt-out.
Closes #97 
---
You can enable it two ways. First, by specifying the `vim.diagnostic.severity`:
```lua
require'bufferline'.setup {
diagnostics = {
[vim.diagnostic.severity.ERROR] = {enabled = true, icon = '⋄'},
[vim.diagnostic.severity.HINT] = {enabled = true},
[vim.diagnostic.severity.INFO] = {enabled = true},
[vim.diagnostic.severity.WARN] = {enabled = true},
},
}
```
Second, by using the `vim.diagnostic.severity`'s index:
```lua
require'bufferline'.setup {
diagnostics = {
{enabled = true, icon = '⋄'}, -- ERROR
{enabled = true}, -- WARN
{enabled = true}, -- INFO
{enabled = true}, -- HINT
},
}
```
---
To do:
> feat: show diagnostic symbols in bufferline

- lua/bufferline/buffer.lua
Apparently, the option `no_name_title` is not quite working. When I set it, even on new buffers it is not used.
In the `lua/bufferline/buffer.lua` file, apparently the "name" variable is getting there as empty string, and then the default `[buffer X]` is being used, so I added a little check in the if statement.
Without the change:
With the change:
This is the barbar config I used:
Since I already came up with a possible solution, I decided to fork and open a PR instead of opening an issue. Sorry if this was not the preferred way. Should I open an issue anyways? Also, I think this solution does not impact other functionalities, but we never know.
And thanks for this plugin and your work for the community! You are awesome (:
> fix(buffer): no_name_title option

- README.md
- doc/barbar.txt
- lua/bufferline/buffer.lua
- lua/bufferline/highlight.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
Adds `BufferAlternate`* series of highlight groups to categorize the previously-active buffer (i.e. the one which will be switched to when pressing `<C-^>`).
```lua
require'bufferline'.setup {
-- enable the distinction of alternate buffers
categories = {alternate = true},
-- hide alternate buffers
hide = {alternate = true},
}
```
The diff will look better after we merge #334.
Closes #140
> feat: highlight alternate buffer

- lua/bufferline/api.lua
- lua/bufferline/buffer.lua
- lua/bufferline/render.lua
Allows use of a `<` check for `api.close_all_but_visible` by making alternate buffers `status == 2` rather than `status == 3`
> perf: c8f972dbab8d90d340cf6e840b73cddc12c350b2

- lua/bufferline.lua
- lua/bufferline/api.lua
This PR adds the `:BufferPickDelete` command, which allows the user to iteratively select buffers which should be deleted (until pressing `<Esc>`).
Closes #73.
To do:
> feat: `BufferPickDelete` command

- lua/bufferline/render.lua
There have been utility functions added to the `options` module which check for these things already, so this is just duplicate code.
> ref(render): deduplicate checks for `icons` options

- README.md
- doc/barbar.txt
- lua/bufferline/buffer.lua
- lua/bufferline/icons.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
Closes #346.
```lua
require'bufferline'.setup {highlight_inactive_file_icons = true}
```
Before:
After:
> feat: `highlight_inactive_file_icons` option

- README.md
The author of `packer.nvim` [uses `lazy.nvim`](https://github.com/wbthomason/dotfiles/blob/main/dot_config/nvim/init.lua#L5) now, so I figured we should provide instructions for that plugin too.
> docs(README): installation instructions for lazy.nvim

- README.md
Closes #355.
Other filetrees don't always name the buffer after the file tree, but most use the filetype.
> docs(README): make filetree integration more universal

- lua/bufferline/buffer.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
Follow the directions in the PR #347. With the changes in this PR, the "pinned" status will be preserved when loading the session.
Closes #361
> feat: persist buffer pins through sessions

- lua/bufferline/render.lua
- lua/bufferline/state.lua
Fixes: https://github.com/romgrk/barbar.nvim/issues/364
About the issue:
The SessionLoadPre is called multiple times for some reason.  If i quickly load a session (when vim start), the first call will unset the pinned (because state.buffers is already set probably).  With this, is prevented to call multiple times so quickly.
This PR Fixes LSP-Zero with session plugins that auto-load session on neovim start.
This is not the best solution but it's work! 
cc @Iron-E
> Fix session load

- README.md
NvimTree and neo-tree are both resizable, this just shows how a user can get that information and use it.
fixes #373
[Screencast from 2023-03-02 17-21-53.webm](https://user-images.githubusercontent.com/61225/222353148-925d3bba-7b03-4754-b2c1-30df59c43f17.webm)
> docs: Update readme with code that works for resizable filetrees

- lua/bufferline.lua
- lua/bufferline/animate.lua
- lua/bufferline/api.lua
- lua/bufferline/bbye.lua
- lua/bufferline/buffer.lua
- lua/bufferline/highlight.lua
- lua/bufferline/icons.lua
- lua/bufferline/jump_mode.lua
- lua/bufferline/layout.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
This makes it so that we don't accidentally do something like this:
```lua
--- @return nil
local function foo()
return true
end
--- @return nil
local function bar()
if some_condition then
-- easier than writing "foo()\nreturn"
return foo() -- error! returns `boolean`
end
-- rest of function
end
```
I also managed to piece together the proper data types for the animations, so I documented those.
> docs: always specify `@return`

- .gitignore
It exposes local usernames; also, the paths change for each person.
> chore(gitignore): LuaLS config

- lua/bufferline/api.lua
- lua/bufferline/state.lua
Closes #367.
This PR adds a fallback for when a buffer is not found in the `state.buffers` list, and the `:BufferNext`/`Previous` command is run:
1. The alternate buffer, if it is in `state.buffers` (as `state.buffers` only lists valid, non-excluded buffers); or
2. `state.buffers[1]`
Fallback incidents are logged using `vim.notify` at log level `INFO`. It is possible to override the `vim.notify` function to filter messages below a certain log level.
> ref: add fallback to `:BufferNext`/`Previous`

- lua/bufferline.lua
- lua/bufferline/api.lua
- lua/bufferline/icons.lua
- lua/bufferline/render.lua
- lua/bufferline/utils.lua
We've been passing around `{title = 'barbar.nvim'}` (to integrate with nvim-notify) in every single_`vim.notify` call. This commit extracts that into `utils.notify`, which will also make it easier should we add any other options that integrate with that plugin.
The diff will improve after merging #369
> ref: integrate with nvim-notify using `utils.notify`

- lua/bufferline/api.lua
Some things returned by `getchar` are not `integer`s, apparently (e.g. `<Left>` and mouse clicks return a string rather than a single keycode). As such, `string.char` does not work on them, and it throws an error when you try to use it how it was being used before.
To fix it, I moved the `string.char` conversion into the `pcall` that already existed for `getchar`.
> fix(api): verbose error bc clicking during `:BufferPickDelete`

- lua/bufferline/icons.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
The problem was that `nvim-web-devicons` resets its highlights using an autocmd on `ColorScheme`, just to make sure that nothing weird happens to the highlight groups it defines as a result of e.g. `:highlight clear` when switching colorschemes. Our `ColorScheme` event was running too soon (i.e. before the devicons event) and as such the icons were all "cleared" upon calling `:colorscheme`.
Closes #382
> fix(icons): being cleared by `:colorscheme`

- README.md
- doc/barbar.txt
- lua/bufferline.lua
- lua/bufferline/bbye.lua
- lua/bufferline/options.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
Closes #368
In a previous request (issue #234, PR #270), it was asked that barbar.nvim mimic the behavior of a browser when closing buffers: choose the buffer to the right of the current buffer.
* __Note:__ I tested FireFox to double check the behavior matched, and found that the current behavior does work as "intended" (i.e. it works like a web browser does).
Code has been added to ensure that the behavior of `:BufferClose` and `:BufferDelete` never differs in the future, since they are supposed to be true synonyms.
To access this feature, simply do:
```lua
require'bufferline'.setup {focus_on_close = 'left'} -- or 'right'
```
---
cc: @sarmong
> feat(bufferline): customize buffer close behavior

- README.md
The `version` tag can make the user experience more stable, since it only updates when we release a new version. Specifically, a new `^1.0.0`-compatible version. This means if we ever released a 2.0 for some reason, users would have to opt-_in_ to it.
> docs(README): lazy.nvim `version` option

- lua/bufferline.lua
- lua/bufferline/animate.lua
- lua/bufferline/api.lua
- lua/bufferline/bbye.lua
- lua/bufferline/buffer.lua
- lua/bufferline/icons.lua
- lua/bufferline/layout.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
I've discovered that there are certain cases where API functions offer a distinct speed advantage over their `vim`-namespace counterparts, and takes advantage of that.
I want to test this for a while before merging.
> perf: use API functions where possible

- README.md
- autoload/bufferline/events.vim
- doc/barbar.txt
- lua/bufferline.lua
- lua/bufferline/api.lua
- lua/bufferline/bbye.lua
- lua/bufferline/buffer.lua
- lua/bufferline/events.lua
- lua/bufferline/highlight.lua
- lua/bufferline/icons.lua
- lua/bufferline/layout.lua
- lua/bufferline/options.lua
- lua/bufferline/render.lua
- lua/bufferline/state.lua
- lua/bufferline/utils.lua
This PR allows customization of the `bufferline.icons` setting per activity / state, like so:
```lua
require'bufferline'.setup {
icons = {
-- Configure the base icons on the bufferline.
buffer_index = false,
buffer_number = false,
close = '',
diagnostics = {…}, -- moved here from the `diagnostics` option
filetype = {
-- Sets the icon's highlight group.
-- If false, will use nvim-web-devicons colors
custom_colors = false,
-- Requires `nvim-web-devicons` if `true`
enabled = true,
},
inactive = {separator = {left = '▎'}},
separator = {left = '▎'},
-- Configure the icons on the bufferline when modified or pinned.
-- Supports all the base icon options.
modified = {button = '●'},
pinned = {button = '車'},
-- Configure the icons on the bufferline based on the visibility of a buffer.
-- Supports …
```
> feat: specify `icons` per buffer activity/state

- README.md
- autoload/bufferline/events.vim
- doc/barbar.txt
- lua/bufferline/options.lua
- plugin/bufferline.lua
Necessary to notify users who still use `vim.g.bufferline` / `g:bufferline` that they must use the `bufferline.setup` function, before we release v2.0.0
Todo:
> ref: deprecate `g:bufferline`

- lua/barbar/config.lua
- plugin/barbar.lua
Closes #402 
Don't auto-call setup if the user did it, as it clears the user options.
> fix: dont call setup if user did it

- README.md
- doc/barbar.txt
- lua/barbar.lua
- lua/barbar/api.lua
- lua/barbar/events.lua
- lua/barbar/state.lua
Closes #202 
Implement basic buffer restore functionality.
This could use some more thought, in particular with regards to session management. My own config has session management enabled so that the closed buffer list is session-local, but I can't make the same assumptions here that I use for my own config so I'll just go with a simpler implementation for now.
> feat: implement buffer restore

- lua/barbar/buffer.lua
- lua/barbar/render.lua
I hoped tuning the offset truncation might fit as a followup to #414 
Truncated text get a bit shifted. The reason for this is afaik found on:
https://github.com/tobealive/barbar.nvim/blob/f31c82d6667f503de558b033006f1426ee169dc7/lua/barbar/render.lua#L677
Adding `+ 2` removes the shift. Since it's nice to give a visual clue when text gets truncated, I added the ellipsis character. I followed the assignment to a variable, which was done in another place. But it's called just twice here, so please let me if you prefer to have it changed.
> feat: improve offset truncation

- .editorconfig
- doc/barbar.txt
This adds an editorconfig, which is supported natively by Neovim 0.9. It automatically sets options that this repo uses.
We can potentially extend it in the future to create inline diagnostics when double quotes are used, etc.
Closes #411
> chore: editorconfig

- lua/barbar/config.lua
- lua/barbar/render.lua
The `custom_colors` option is not named consistently.
Indeed, I was able to find two mentions of `custom_color` which I suppose are typos.
> fix: typo custom_color -> custom_colors

- .editorconfig
Just run `vim.lsp.buf.format()` (or equivalent) with Neovim 0.9+ or [editorconfig.nvim](https://github.com/gpanders/editorconfig.nvim) installed.
---
Closes #430
> chore(editorconfig): add emmylua settings

- README.md
- doc/barbar.txt
- lua/barbar/config.lua
- plugin/barbar.lua
Enables users to disable the auto-setup in `plugin/barbar.lua`. All you have to do is:
```lua
vim.g.barbar_auto_setup = false
```
```vim
let g:barbar_auto_setup = v:false
```
---
Closes #431
> feat: disable auto-setup

- README.md
- doc/barbar.txt
- lua/barbar/api.lua
- lua/barbar/bbye.lua
- lua/barbar/buffer.lua
- lua/barbar/config.lua
- lua/barbar/events.lua
- lua/barbar/layout.lua
- lua/barbar/render.lua
- lua/barbar/state.lua
- lua/barbar/utils.lua
Pinned buffers now always stay visible in the bufferline. Additionally, they take up less space— they use the minimum padding, and no longer show a filename or pin icon by default. 
To restore the old pinned buffer look, do:
```lua
require'barbar'.setup {
icons = {
pinned = {
button = '',
filename = true,
separator = {right = ''},
},
},
}
```
Todo:
---
Closes #393.
Closes #401.
> feat: pinned buffers stay visible

- lua/barbar/buffer.lua
> fix(buffer): buffer name cut off at `<e2>`

- lua/barbar/bbye.lua
- lua/barbar/events.lua
Certain buffers show a message when trying to close them (e.g. `:terminal`s) if you do not `:confirm` their closure. This was getting picked up by the `bbye` (since it is not a `v:errmsg`).
To fix it, I have switched from using `v:errmsg` to the `pcall`'s `result` return value.
However, if we left it at that, it would be impossible to click to close certain windows (since they need `:confirm`). Thus I have added `:confirm` as a modifier to the close click handler.
---
Closes #449.
> fix: close click confirmation message reports error

- lua/barbar/config.lua
- lua/barbar/render.lua
This PR does two things to increase performance:
1. Only use `deepcopy` on the default icons, not the whole default options table. 
* We only need to `deepcopy` at all because the icons are merged together, and sometimes share references to each other.
2. Only prevent expansion of the final click group if there are click groups in the bufferline.
* I noticed that, since I have `clickable = false` in my config, that this was the only click handler in the barbar at all. The reason for it being there is only to prevent bugs when `clickable == true`, so we can avoid making a new string per render in this case.
> perf: misc

- lua/barbar/ui/layout.lua
Regression introduced in https://github.com/romgrk/barbar.nvim/commit/202e51e967b79e82832f537ddb29d35af991de90.
Closes #453.
> fix(layout): attempt to calculate width of invalid buffer

- README.md
- doc/barbar.txt
- lua/barbar/config.lua
- lua/barbar/state.lua
- lua/barbar/ui/render.lua
Thanks for the maintenance. It's nice to see the repositories active development.
This PR extends the options for buffer indices and numbers with the style options `'superscript'` and `'subscript'`. Current boolean values will continue to work as they are. 
I did my best to follow the conventions I've seen in the repo.
> feat: add number styling

- doc/barbar.txt
Noticed a missing reference when looking through help files, here is a small pr
> docs: table of contents reference

- lua/barbar/icons.lua
It is possible to define new icons with `nvim-web-devicons`, and _not_ define a color for them.
Closes #482
> fix(icons): check for `get_icons` returning `nil`

- README.md
- doc/barbar.txt
- lua/barbar/bbye.lua
- lua/barbar/config.lua
The default is now also `'previous'`, since that is what users of other IDEs would expect.
Closes #465.
> feat: `focus_on_close = 'previous'`

- README.md
- doc/barbar.txt
- lua/barbar/config.lua
- lua/barbar/events.lua
- lua/barbar/highlight.lua
- lua/barbar/utils/highlight.lua
Makes it easier to use commonly desired icon configurations.
```lua
require'barbar'.setup {
icons = {
preset = 'powerline', -- 'default' and 'slanted' are also valid
-- other options
},
-- other options
}
```
---
Closes #141
> feat: `icons.preset`

- README.md
The code for mini.nvim session integration is incorrectly labelled as being for persistence.nvim
> docs: fix incorrect label for the mini.nvim integration code

- lua/barbar/events.lua
Creates default `BufWinLeave` autocmd and appends custom `option.event` if it differs from the default. 
Fails silently using `pcall` if the other event already deleted the `autocmd` from line 192.
Closes #502
Tested with "print debugs"
```lua
local ok, _ = pcall(del_autocmd, autocmd)
if not ok then
print("couldn't delete autocmd", vim.inspect(autocmd), vim.inspect(e))
else
print("deleted autocmd", vim.inspect(autocmd), vim.inspect(e))
end
```
> fix(events.lua): Listen for default and user-configured sidebar_filetype close events

- README.md
There is a comma in `packer.nvim` in `README.md` installation section, which, when running `:PackerSync`, causes below error:
```
Error detected while processing :source (no file):
E5107: Error loading lua [string ":source (no file)"]:27: unexpected symbol near ','
```
> doc: remove invalid comma

- .gitignore
Makes it so `:helptags ALL` does not modify the state of the repo.
> chore(gitignore): ignore doc/tags

- lua/barbar/events.lua
From `:h news`:
> Terminal buffers started with no arguments (and use 'shell') close
> automatically if the job exited without error, eliminating the (often
> unwanted) "[Process exited 0]" message.
Closes #522
> fix(events): `:term` stays open after job finishes on 0.10-nightly

- lua/barbar/buffer.lua
- lua/barbar/ui/layout.lua
- lua/barbar/ui/render.lua
Closes #525
Changes the `hide()` function so that `pinned` buffers are still shown, even if the `hide` config setting would normally apply to them. I figure that hiding a pinned buffer is probably not desired behavior.
> ref: always show pinned buffers, even with `hide`

- README.md
- doc/barbar.txt
- lua/barbar/config.lua
- lua/barbar/ui/render.lua
Closes #528 
Users can now specify how many buffers they would like to tolerate before showing the tabline, e.g. `auto_hide = 0` for hiding the tabline when there are zero buffers left. 
The old values, `false` and `true`, have been translated into `-1` and `1` respectively. This is not a breaking change— it happens silently during `setup`.
> Customizable `auto_hide` count

- lua/barbar/api.lua
- lua/barbar/events.lua
- lua/barbar/state.lua
- lua/barbar/ui/render.lua
Closes #261 
The feature is automatically enabled when `clickable = true` during `setup`.
Todo:
> feat: reorder buffers with mouse drag

- lua/barbar/highlight.lua
- lua/barbar/icons.lua
- lua/barbar/utils/highlight.lua
Closes #547 
`underdouble` etc. are only available 0.8+
> fix: reference to nvim 0.8 highlight attributes when on nvim 0.7

- lua/barbar/events.lua
Closes #560
Sidebar width was allowed to be less than zero, which caused errors in subsequent layout calculations
> fix(events): sidebar width calculation

- README.md
- doc/barbar.txt
- lua/barbar/events.lua
- lua/barbar/state.lua
Closes #556 
```lua
require('scope').setup {
hooks = {
pre_tab_leave = function()
vim.api.nvim_exec_autocmds('User', {pattern = 'ScopeTabLeavePre'})
-- [other statements]
end,
post_tab_enter = function()
vim.api.nvim_exec_autocmds('User', {pattern = 'ScopeTabEnterPost'})
-- [other statements]
end,
-- [other hooks]
},
-- [other options]
}
```
> feat: scope.nvim integration

- doc/barbar.txt
Enables TS highlighting for our vimdoc. Diff will look better after #559 merges
> style(vimdoc): TS syntax highlighting

- lua/barbar/bbye.lua
There were a couple edge cases I discovered with the previous PR (#563), namely:
* Not all "buffer reference literals" were detected. Race conditions also occurred when doing, e.g. `:BufferDelete $`
* Older devices may finish events in different orders. This implementation is deterministic.
> fix(550): buffer close references

- lua/barbar/api.lua
- lua/barbar/bbye.lua
- lua/barbar/constants.lua
- lua/barbar/events.lua
- lua/barbar/state.lua
- lua/barbar/ui/layout.lua
- lua/barbar/ui/render.lua
Closes #550
Avoid focusing back on a closing buffer.
> Fix state management issues

- README.md
- doc/barbar.txt
I'm using [persisted.nvim](https://github.com/olimorris/persisted.nvim) as a session manager and I followed its [docs](https://github.com/olimorris/persisted.nvim?tab=readme-ov-file#events--callbacks) to integrate buffer saving with barbar, which can be added to the docs in case anyone wants to do the same.
> docs: add persisted.nvim to sessions integration

- lua/barbar/events.lua
`layout.buffers` was moved in #573 to `state.buffers_visible`
See #576
> fix(events): reference to `layout.buffers`

- lua/barbar/bbye.lua
Sometimes I met such error when use `BufferClose` to delete current buffer:
I add a `win_is_valid` check before calling `set_current_win` API.
> fix(bbye): fix switch window failure

- lua/barbar/events.lua
> fix: use of deprecated `vim.tbl_islist`

- lua/barbar/events.lua
This should resolve #583. The `DiagnosticChanged` event was firing when closing buffers, causing Barbar to try to render a nonexistent buffer. I just added an if statement to account for this; it seems to work in my testing now.
> fix: add check to ensure that buffer is loaded

- README.md
- doc/barbar.txt
- lua/barbar/api.lua
- lua/barbar/config.lua
Closes #596.
This PR implements an option to enable case-insensitive sorting in barbar.nvim:
```lua
require'barbar'.setup {
sort = { ignore_case = true },
}
```
Documentation was added, and the existing sorting functions were updates to respect the user's configuration.
> feat: case-insentive sorting

- lua/barbar/events.lua
It turns out that our gitsigns update autocmd was occasionally looking in the wrong place for the number of the buffer that had its signs updated.
It seems that it gitsigns may issue a secondary buffer number in the user data event field when the buffer whose signs were updated is different than the current buffer. I am not positive on the reason for this, but I will assume that it was well-informed.
Closes #604
> fix(events): respond to gitsigns update in remote buffers

- lua/barbar/state.lua
Pull request to fix the tab title not obeying min/max length as a result of `format_name` not being called
> fix: tab title not obeying min/max length

- README.md
- lua/resession/extensions/barbar.lua
Adds an extension for https://github.com/stevearc/resession.nvim to session save and session restore using resession. Fixes resession bug https://github.com/stevearc/resession.nvim/issues/63 and is also (imo) generally a bit nicer of a solution than using globals. Ideally this becomes the "most advisable" way of doing session management using barbar - this seems to work pretty damn flawlessly in my testing, having spent a while using persisted.nvim.
Note that the code is mostly based off of how barbar was already doing session save and session restore.
> Add resession extension support

- lua/barbar/events.lua
- lua/barbar/highlight.lua
It seems that we had an oversight in determining when the highlight
cache needed to be invalidated. We listened for the colorscheme to be
swapped, but not for mutations to the current colorscheme.
One such mutation is `set bg=dark` vs `set bg=light`. This typically
does not emit a `ColorScheme` event, but still requires us to invalidate the highlight cache and setup highlights.
To fix this, I have added an `autocmd` for `OptionSet background` which resets highlighting.
Closes #624
> Reset highlights when `&bg` changes

- lua/barbar/api.lua
- lua/barbar/buffer.lua
- lua/barbar/fs.lua
After some discussion in #612, it was determined that we should expand upon the proposed set of changes in order to standardize how we handle filepaths throughout the plugin.
- The implementation leans into Neovim 0.8 features where available
- On Neovim 0.7, we provide basic implementations of those features to maintain compatibility
I'd like to give credit to @exzolink for figuring out how to solve #611 and presenting a solution which we could easily encapsulate!
- filepath utilities
- update handling of filepaths
- Closes #611
- Closes #612
> Normalize filepaths

- lua/barbar/fs.lua
Check that ```vim.fs.joinpath``` is not nil before trying to reuse it, it appears that it is missing in some versions of neovim: https://vi.stackexchange.com/questions/44597/why-is-vim-fs-joinpath-missing-from-neovim-0-9-5-on-macos
> fix: check that vim.fs.joinpath is not nil (#630)

- lua/barbar/highlight.lua
how it is:
how it should be:
both the slanted and powerline presets enforce underlines there.
in case you think this IS necessary, let me know, so I can change it to a configuration preset instead.
> remove hard-coded underlining

- lua/barbar/buffer.lua
fnamemodify was using the wrong modifier to grab the filename without the extension. This fixes that
> fix: use the correct modifier to remove file extensions (#639)
