README.md
doc/barbar.txt
plugin/bufferline.vim

Include v by default in bufferline.letters

---

README.md
doc/barbar.txt

tabpages indicator added to README.md

docs: tabpages indicator

---

lua/bufferline/utils.lua

Sorry for the embarrassing mistake

remove trailing whitespace

---

README.md

Utilizing `autocmd` to integrate genericly to filetree plugins

---

lua/bufferline/bbye.lua

fix(bbye): check buf is listed rather than loaded

---

lua/bufferline/render.lua

This is a character that is integral to the syntax of the tabline setting. To fix this, I had to escape all '%' in a buffer name with '%%', which renders '%' literally.
Figuring out an elegant solution to this was a little challenging, as barbar previously assumed that all characters in a given `group[2]` were visible characters (i.e. characters that take up space on the screen). To get around this, I added `group[3]`, which is the LITERAL string that is shown on screen, while `group[2]` is now the string which is used in the tabline in order to render `group[3]`.
Closes #235

fix(render): buffers with '%' in the name

---

lua/bufferline/bbye.lua

I will push any fixes I find here.
Closes #231 and #238.

fix #231 and #238

---

README.md

docs(README): recommend using `bufferline.setup`

---

lua/bufferline/buffer.lua

fix(buffer): reference to invalid buffer `number`

---

lua/bufferline.lua
lua/bufferline/bbye.lua
lua/bufferline/buffer.lua
lua/bufferline/layout.lua
lua/bufferline/render.lua
lua/bufferline/state.lua

Closes #252 
Replace all `vim.bo` uses with `nvim_buf_[gs]et_option`.

fix: option issue (closes #252)

---

lua/bufferline.lua
lua/bufferline/bbye.lua
lua/bufferline/buffer.lua
lua/bufferline/highlight.lua
lua/bufferline/icons.lua
lua/bufferline/layout.lua
lua/bufferline/state.lua
lua/bufferline/utils.lua

A new version of Sumneko's Lua Language Server was released, and as such
new potential error points were revealed. This commit resolves them.

chore: cleanup diagnostics

---

lua/bufferline.lua
lua/bufferline/jump_mode.lua

fix(jump_mode): reassign jump letters after freeing another letter

---

lua/bufferline.lua
lua/bufferline/bbye.lua
lua/bufferline/state.lua

Closes #234 
Focus the tab on the right when after closing a tab.

feat: improve close behavior

---

lua/bufferline.lua

fix(bufferline): not updating when Nvim opens w/ tabs

---

README.md
autoload/bufferline.vim
doc/barbar.txt
lua/bufferline.lua
lua/bufferline/animate.lua
lua/bufferline/api.lua
lua/bufferline/bbye.lua
lua/bufferline/buffer.lua
lua/bufferline/highlight.lua
lua/bufferline/icons.lua
lua/bufferline/jump_mode.lua
lua/bufferline/layout.lua
lua/bufferline/render.lua
lua/bufferline/state.lua
lua/bufferline/utils.lua

Add option to define minimum padding

---

README.md
doc/barbar.txt
lua/bufferline.lua
lua/bufferline/api.lua

feat: Add new command `:BufferCloseAllButVisible`

---

lua/bufferline/jump_mode.lua
lua/bufferline/options.lua
lua/bufferline/render.lua
lua/bufferline/state.lua

fix: buffer close animations

---

lua/bufferline/bbye.lua

fix(bbye): `BufferCloseAll*` commands

---

lua/bufferline/icons.lua
lua/bufferline/layout.lua
lua/bufferline/render.lua
lua/bufferline/state.lua

fix: assuming file icon is single char width

---

lua/bufferline/buffer.lua

fix(buffer): multi-code-point chars cut off

---

README.md

docs(README): update `nvim-web-devicons` repo link

---

lua/bufferline/render.lua

fix(render): scroll animates when animation disabled

---

lua/bufferline/layout.lua
lua/bufferline/options.lua
lua/bufferline/render.lua

fix: `buffer_numbers` not accounted for in `layout`

---

README.md
doc/barbar.txt

You know what they say: if it isn't documented, it might as well not exist…

docs: `:BufferPickDelete`

---

lua/bufferline/render.lua

The old implementation only worked for a specific fork of an unmaintained plugin (see https://github.com/romgrk/barbar.nvim/pull/316#issuecomment-1281697110). This is a more general implementation that can be  used with other plugins.
Requires `vim.opt.sessionoptions:append 'globals'` in your config. Make sure to `:doautocmd User SessionSavePre` _before_ saving your session (ideally your session plugin does this automatically, but if not, you can create a wrapper command easily enough). Then, upon `SessionLoadPost`, the order of buffers will be restored.
---
Closes #345.

feat(render): restore buffer order with session restore

---

lua/bufferline.lua

Adds tab completion to the `:BufferGoto` command. The completions are the already open buffers as indexes, and their negative counterparts (since `:BufferGoto -1` is valid).

feat(bufferline): `:BufferGoto` completion

---

lua/bufferline.lua

Merge resolutions must have knocked this line out.

fix(bufferline): un-imported `utils`

---

lua/bufferline.lua
lua/bufferline/api.lua
lua/bufferline/bbye.lua
lua/bufferline/buffer.lua
lua/bufferline/highlight.lua
lua/bufferline/icons.lua
lua/bufferline/jump_mode.lua
lua/bufferline/layout.lua
lua/bufferline/render.lua
lua/bufferline/state.lua
lua/bufferline/utils.lua

See the commit message: 882f48aa14e2dfd94bf28f7021d319153bc1aa25

docs: remove excessive type annotations

---

lua/barbar/render.lua

feat: check offset width for multibyte characters

---

lua/barbar/render.lua

fix(render): ellipsis changes layout

---

lua/barbar/animate.lua
lua/barbar/fs.lua
lua/barbar/layout.lua
lua/barbar/render.lua
lua/barbar/state.lua

A few things happening here:
- Some refactoring:
- Split `render.update(...)` in two, extract tabs calculation
- Move out impure side-effects
- Rename some fields, mainly `real_...` to `computed_...`
- Fix the open & close animation
- Increase the animation frequency, make it feel smoother
@Iron-E This might conflict with some of your changes but I'd rather we merge this first, these changes will help us maintain the plugin better.

fix: animations

---

lua/barbar/state.lua

I'm getting this error when I open sessions, occasionally:
```
Error executing vim.schedule lua callback: /home/romgrk/src/barbar.nvim/lua/barbar/state.lua:333: Invalid  buffer id: 14f
```

fix: error invalid buf

---

README.md

@romgrk any nits on the phrasing?

docs(README): we don't support `netrw`

---

lua/barbar/api.lua
lua/barbar/config.lua
lua/barbar/groups.lua
lua/barbar/highlight.lua
lua/barbar/layout.lua
lua/barbar/render.lua

Changes:
- Move groups functions in their own file
- Use dedicated rendering functions
Closes #68

Refactor and more

---

README.md
autoload/bufferline.vim
doc/barbar.txt
lua/barbar/events.lua
lua/barbar/highlight.lua

Typo corrections.
edit: I probably had a faulty assumption about a relation to #409 and an `if`/`iff` inconsistency. Therefore slimmed down the changes on my side. Thanks a lot for all the recent improvements!

fix: typos

---

lua/barbar/ui/render.lua

Regression in 31b4aa072bbe15cfe2b58c26d787025743b9c1ca

fix(render): pinned buffers

---

lua/barbar/events.lua
lua/barbar/state.lua

1. When a session loads that has multiple working directories (i.e. `:lcd`/`:tcd`), buffers will always be named relative to the *current* working directory (i.e. the output of `getcwd()`). This means we have to save file paths relatively.
2. `bufadd` doesn't seem to work like we thought. It always seems to add a new buffer first (regardless of whether it exists), and then return the new buffer on repeated calls. 
* The documentation states that _if a buffer exists with a given name_, it will return that buffer instead of creating it. But that seems to be only half true.
Closes #467

fix: use `bufnr()` when loading session

---

README.md
doc/barbar.txt
lua/barbar/highlight.lua
lua/barbar/ui/render.lua

feat: `Buffer<Activity>SignRight` highlight

---

lua/barbar/ui/render.lua

ref(render): scroll to fill tabline when closing a buffer

---

lua/barbar/events.lua

fix(events): attempt to operate on invalid buffer

---

lua/barbar/highlight.lua
lua/barbar/ui/render.lua

These aren't "special" per se, but a delimiter and number respectively.

ref(highlight): make `Arrow` and `Tabpages` default hl more semantic

---

lua/barbar.lua
lua/barbar/api.lua

E.g. `:1BufferPickDelete`, `:BufferPickDelete 2`, `vim.cmd.BufferPickDelete {count = 3}`
---
Closes #494

feat: provide count of buffers to pick delete

---

README.md
lua/barbar/icons.lua

Patch packer devicons documentation and warning

---

lua/barbar/highlight.lua

This was unintentional, I meant to adjust the fg.

fix(highlight): `BufferTabpageFill` highlight changed

---

README.md
doc/barbar.txt
lua/barbar/config.lua
lua/barbar/ui/render.lua

feat: option for displaying a trailing separator

---

lua/barbar/utils/highlight.lua

fix(utils): `reverse` attribute not accounted for

---

README.md
doc/barbar.txt
lua/barbar/config.lua

Closes #521.
See-also: de37647f05a5b556b6426b78c4608bbd40a8089f

fix: ensure compatibility with Nerd Fonts v3

---

README.md
doc/barbar.txt
lua/barbar/api.lua
lua/barbar/config.lua
lua/barbar/events.lua
lua/barbar/highlight.lua
lua/barbar/state.lua
lua/barbar/types.lua
lua/barbar/ui/render.lua

Closes #538 
```lua
require'barbar'.setup {
sidebar_filetypes = {NvimTree = {text = 'foobar', align = 'right'}} -- or `'left'|'center'`
}
```

feat: align `BufferOffset` text

---

lua/barbar/bbye.lua

Closes #550 
Currently, attempting to close the "current" buffer repeatedly in a short span of time results in surprising behavior. This is caused by the following two locations in the codebase:
* https://github.com/romgrk/barbar.nvim/blob/master/lua/barbar/events.lua#L177-L184
* https://github.com/romgrk/barbar.nvim/blob/master/lua/barbar/bbye.lua#L128-L133
Specifically, the interaction is that the calls to `bbye.delete` read `state.buffers` before `render.update` has had a chance to update it.
The fix here has been to implement an asynchronous, sephamore-like counter which must become available before actions on the "current" buffer can be performed.

fix(bbye): "current buffer" deletion race condition

---

lua/barbar/buffer.lua
lua/barbar/state.lua
lua/barbar/utils/list.lua
lua/barbar/utils/table.lua

fix: make unique names work

---

lua/barbar/buffer.lua
lua/barbar/state.lua
lua/barbar/utils/list.lua
lua/barbar/utils/table.lua

fix: unique names

---

README.md
doc/barbar.txt
lua/barbar.lua
lua/barbar/api.lua

feat: order by name

---

lua/barbar/bbye.lua

Fixes case where `:BufferClose` had no effect.

Fix buffer close

---

README.md
doc/barbar.txt
lua/barbar.lua
lua/barbar/api.lua

Closes #609 
Add commands `BufferGotoPinned` and `BufferGotoUnpinned`.

feat: goto pinned/unpinned
